<?php

namespace app\modules\apiv1\controllers;

use yii;
use app\modules\apiv1\models\LoginForm;
use yii\rest\ActiveController;

class UserController extends ActiveController
{
    public $modelClass = 'app\modules\apiv1\models\User';

    public function actions()
    {
        $action = parent::actions(); // TODO : Change the autogenerated stub
        unset($action['index']);
        unset($action['create']);
        unset($action['update']);
        unset($action['delete']);
    }

    public function actionIndex()
    {
    }

    /**
     * landing
     * @return array
     * @throws \yii\base\Exception
     * @throws \yii\base\InvalidConfigException
     */
    public function actionLogin()
    {
        $model = new LoginForm();
        if ($model->load(yii::$app->getRequest()->getBodyParams(), '') && $model->login()) {
            return [
                'accessToken' => $model->login(),
            ];
        } else {
            return $model->getFirstErrors();
        }
    }
}
